### ISSUE TITLE
Support Notification.set_icon

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/notifications#111]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
As title implies. Using `set_icon` doesn't change the icon. Not entirely sure but it could be because the notifications server sets the app icon to be the icon that's specified in the .desktop file.

https://github.com/elementary/notifications/blob/749e28b31117af522b6337f055f0e237fea44d6e/src/Notification.vala#L89-L95

### To Reproduce
```vala
// valac --pkg gtk+-3.0 Application.vala

public class Application : Gtk.Application {
    public Application () {
        Object (
            // Set icon to calculator so an icon does show
            application_id: "io.elementary.calculator",
            flags: ApplicationFlags.FLAGS_NONE
        );
    }

    protected override void activate () {
        var notification = new Notification ("Test");
        notification.set_icon (new GLib.ThemedIcon ("application-pdf"));
        notification.set_body ("123");

        send_notification (application_id, notification);
    }

    public static int main (string[] args) {
        var app = new Application ();
        return app.run (args);
    }
}

```

### Expected behavior

Using the above code sample, the icon should show an "application-pdf" icon

## Platform Information
- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by pongloongyeat** [comment]
It could also be because the notifications server doesn't make use of an `image-path` parameter?

```
Type:    method-call
Flags:   none
Version: 0
Serial:  72
Headers:
  path -> objectpath '/org/freedesktop/Notifications'
  interface -> 'org.freedesktop.Notifications'
  member -> 'Notify'
  destination -> 'org.freedesktop.Notifications'
  sender -> ':1.79'
  signature -> signature 'susssasa{sv}i'
Body: ('', uint32 0, '', 'Task finished', 'sleep 5', @as [], {'desktop-entry': <'io.elementary.terminal'>, 'urgency': <byte 0x01>, 'image-path': <'utilities-terminal'>}, -1)
UNIX File Descriptors:
  (none)

```

Though I'm not entirely sure this should be `image-path` here but rather something like `icon-name`.

**Comment by pongloongyeat** [comment]
I've just realised that the third blank parameter in "Body" should be the `app_icon` string. So it should look like this

```
method-call
Flags:   none
Version: 0
Serial:  76
Headers:
  path -> objectpath '/org/freedesktop/Notifications'
  interface -> 'org.freedesktop.Notifications'
  member -> 'Notify'
  destination -> 'org.freedesktop.Notifications'
  sender -> ':1.61'
  signature -> signature 'susssasa{sv}i'
Body: ('', uint32 0, 'media-removable', 'Kingston DataTraveler 2.0 connected', 'With 1 volume present', @as [], {'desktop-entry': <''>, 'urgency': <byte 0x01>}, -1)
UNIX File Descriptors:
  (none)

```

But I am not entirely sure how to reproduce this. Does it have something to do with there being no desktop entry present?

**Comment by pongloongyeat** [comment]
Since `image_path` is set to the icon name of whatever `Notification.set_icon` was parsed, a workaround would be to set `app_icon` to be `image_path` if `image_path` doesn't actually point to a path. This is pretty wobbly but should do the job for now at least.

```vala
if ((variant = hints.lookup ("image-path")) != null || (variant = hints.lookup ("image_path")) != null) {
            image_path = variant.get_string ();

            if (!image_path.has_prefix ("/") && !image_path.has_prefix ("file://")) {
                /* app_icon should be set to image_path here if the image_path parameter
                isn't a path to a file. Should try to find a way to check if an icon
                is actually valid so if the icon string doesn't exist, we'll fallback
                to dialog-information. */
                app_icon = image_path;
                image_path = null;
            }
        }
```

**Comment by pongloongyeat** [comment]
> This a kind of problematic in that it makes it unclear which app has sent a notification. If we want to support apps sending icon names to the server, it should be done similar to images where we have a badge so the app's icon is always shown

**Comment by danrabbit** [comment]
We now support both named icons and file icons set on the `image-path` hint, so this issue should be considered closed :)
