### ISSUE TITLE
Transparent bubbles and 'other' missing

### ISSUE THREAD

**Issue by pheonixo** [elementary/notifications#179]
## Describe the bug
Notification bubbles of notices are unreadable but can still see icon of sender. 100% transparent doesn't work for me and no css setting I can determine. Using elementary theme, which thankfully installed tweaks to set since just installing was a nightmare coming from os 5. The 'other' are notifies like new kernel releases, which I can tell occur because of package icon, and can see faint wording if stare hard and fast. They are no longer included in the notification pop-down list.
There are other notify issues but think they go to actual apps? like AppCenter and Mail. Though mail I had to stop using and replaced with geary and notify on that works fine, closely approximates OS5 and can send mail.

### To Reproduce
update to Ubuntu 20.04.3 which installs OS6
run os6
wait for notify, can install Ubuntu mainline if want to force 'other' messages

### Expected behavior
To run like OS 5 or at least a setting or clue how to change transparency on bubbles.

## Platform Information
Ryzen 2400g Ubuntu 20.04.3 kernel 5.18.12-igpu
OS 6.1 latest
from:
ppa.launchpad.net/elementary-os/stable/ubuntu focal InRelease
ppa.launchpad.net/elementary-os/os-patches/ubuntu focal InRelease

**Comment by pheonixo** [comment]
Did an apt reinstall of notifications (read that 6 removed from window manager), reboot, no joy! Then tried reinstall of pantheon (assumed not disconnected as read), reboot, no joy! This has become extremely annoying, considering there is no way to install Hera. I got dependent on notifications, other problems with notifications can be overlooked, but solution of a white desktop won't cut it, just to read event.
Update Platform Information:
Ubuntu 20.04.5 with 5.18.19 kernel

**Comment by pheonixo** [comment]
Update from apt approximate 20 November, has now pushed to urgent. Sound notifications now infected by bad coding. Non-messaging web pages that use video players create stack of non-removable messages. Only solution is to reboot after using web browser to set up for next reboot.
![image10](https://user-images.githubusercontent.com/93680335/203402104-79e57e92-968c-4fff-942d-e2dcf405db67.png)

**Comment by janxkoci** [comment]
Direct distro upgrades are **not officially supported**, no wonder you experience problems. Some components probably didn't get installed properly.

The official advice will most likely be something like "do backup and a fresh install", although the team is working on making upgrades work in the future, so maybe this report can be catalogued for that purpose...

**Comment by danirabbit** [comment]
Yeah gonna close since this is an old issue and you can see stylesheet related bugs in the screenshot here. This is definitely caused by unsupported upgrade path
