### ISSUE TITLE
Spotify ignores notification settings

### ISSUE THREAD

**Issue by maxlStone** [elementary/notifications#180]
### What Happened?

Spotify still notifies on song change although the notification settings are turned off.

### Steps to Reproduce

1. Run a playlist in spotify
2. Disable notification settings
3. See the notifications up right on song change

### Expected Behavior

Spotify should follow the settings

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

- Latitude-E7270-51d14d9f
- Intel® Core™ i7-6600U CPU @ 2.60GHz
- Intel® HD Graphics 520 (Skylake GT2)

**Comment by Marukesu** [comment]
this's a issue with the Spotify flathub package, i believe it's send `spotify`, but we are expecting `com.spotify.Client` since flatpak will rename the desktop file to use the flatpak id. Not sure if there's something they can do about it.

Closing as it isn't a issue with the daemon.
