### ISSUE TITLE
Pop-up notifications persist on screen even after cursor hovers away 

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/notifications#220]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Pop-up notifications persist on the screen when the mouse cursor hovers over them and moves away, they do not minimize and automatically go into the notifications bar. 

### To Reproduce
Happens only occasionally, no known way to reproduce.

### Expected behavior
The pop-up should close after x number of seconds (I think it is set to 1s by default) and go into the notifications bar (the bell icon).

## Platform Information
 - elementary OS 5.1 Hera
 - Dell XPS 13 9380 Dual Booted

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
If there is a feature to disable that i.e even if the cursor hovers over the notification, the pop-up closes after x number of seconds, that would be great.

**Comment by Marukesu** [comment]
I'm closing this. There was some changes in the daemon since the time of the report, one of it was #114 that probably should have fixed this too.

If someone can still reproduce it, we can re-open.
