### ISSUE TITLE
Sanitize body text

### ISSUE THREAD

**Issue by danrabbit** [elementary/notifications#26]
Getting errors about things like unescaped ampersands

**Comment by cassidyjames** [comment]
This is open again because the fix broke markup:

![image](https://user-images.githubusercontent.com/611168/60306785-e73a8d00-98fe-11e9-882d-b506e1705a4e.png)

inspecting shows the label contents to be `Approximately &lt;b&gt;1 hour 12 minutes&lt;/b&gt; remaining (9%)`
