### ISSUE TITLE
Music notifications are oversized

### ISSUE THREAD

**Issue by danrabbit** [elementary/notifications#31]
![Screenshot from 2019-06-13 15 25 25@2x](https://user-images.githubusercontent.com/7277719/59471312-93548200-8def-11e9-9162-4894000dd93c.png)

Maybe something to do with the body markup forcing a newline?

**Comment by cassidyjames** [comment]
Should we support newlines in notifications at all?

**Comment by cassidyjames** [comment]
…because I can currently do this! :sweat_smile: : ![image](https://user-images.githubusercontent.com/611168/59473453-b9821e00-8dff-11e9-8bea-5361302c3ac3.png)

**Comment by cassidyjames** [comment]
I guess [`string.strip ()`](https://valadoc.org/glib-2.0/string.strip.html) would also be fine.

**Comment by danrabbit** [comment]
I feel like for this specific usecase that having one newline is nice, but I don't feel like we should support more than a handful of lines in a notification. Gala was really dumb about this and you could get some ridiculous large notifications from Slack, for example

**Comment by cassidyjames** [comment]
@danrabbit I'd still say strip is what we want minimally since it takes care of any leading and trailing whitespace—I don't lnow why we'd ever want leading or trailing whitespace, anyway.

**Comment by danrabbit** [comment]
@cassidyjames I can't confirm that adding a `strip ()` fixes this issue unfortunately
