### ISSUE TITLE
Notification timeout setting

### ISSUE THREAD

**Issue by weelillad** [elementary/notifications#40]
It would be nice to have a configuration setting to determine how long the notification display is, because I find the current default a little too short.

**Comment by danrabbit** [comment]
I'm inclined to mark this as "Design Conflict" for a few reasons:

1. If you'd like to keep a notification around for extra time, you can hover over it and it will stay until your mouse leaves the notification. In this way, there is already fine grained control over adding additional time to a notification

2. The notification center exists for you to be able to review any missed notifications. So there is no real penalty to a notification having timed out before you are able to digest its information. 

3 And for notifications for which there is a penalty (like power notifications), there is no timeout. So critical notifications will stay on screen until they are dismissed manually.

**Comment by cassidyjames** [comment]
@danrabbit I think I agree with you. 

I also think something GNOME Shell does that's relevant and could mitigate the need for a specific setting is that it doesn't start counting down the time until there is user activity (i.e. mouse or keyboard). This way if you look/step away from the display for a moment and would otherwise miss a notification, when you come back it's there for a moment before going away.

Out of scope of this issue specifically, but something to think about at least.

**Comment by cassidyjames** [comment]
Ah another note that might be relevant: Android (and possibly other OSes?) has a “time to take action” setting intended for accessibility. It's an interesting thought at least and could potentially affect notifications, toasts, and anything else that comes on screen temporarily. The idea being that if you have specific motor control needs, those default timeouts could be problematic at worst or at least annoying.

![Screenshot_20200113-140906](https://user-images.githubusercontent.com/611168/72292380-85c5db80-360e-11ea-8ce9-17d19125c105.png)

**Comment by weelillad** [comment]
Thanks for taking time to address the issue. I accept that this might be a design conflict.

Just for context, my use case was office Slack notifications. The message is displayed in full in the notification, which is great because people don't tend to begin with a good topic sentence on instant messaging. I'm working on a document in a maximized window so I don't want to Alt-Tab to see what the message is about, yet I want be able to skim through the message and see if it warrants an immediate reply. My current solution is having the Slack window permanently open on a second monitor.

**Comment by cassidyjames** [comment]
@weelillad yeah in that case I think the ideal thing would be to hover the notification with your mouse so you can read it before it goes away. _Maybe_ something else for us to consider could be a dynamic notification timeout based on the length of the notification, though I think we may plan to truncate after a couple of lines; notifications aren't really intended for super long-form messages.

**Comment by danrabbit** [comment]
Yeah in master notifications are truncated after 2 lines
