### ISSUE TITLE
Apps can set background/text color for Notifications

### ISSUE THREAD

**Issue by lainsce** [elementary/notifications#46]
For example, if one changes the Music playing, the album art dictates colours for the Notification in for ex. Android:

![](https://i.imgur.com/8kEb0O2.jpg)

May need some modifications in code in apps and the Notification Center, but I think this is a good idea.

**Comment by cassidyjames** [comment]
Hm, on Android it is actually the OS that sets the background and foreground color afaik, because it does this for all media-playback-type notifications using the color palette API. I believe apps may _also_ be able to set some styling, but I'm not sure how that interacts with the system-wide dark style.

**Comment by lainsce** [comment]
I have no way of knowing Android's global dark styling because I have no phones with Android 10. :disappointed:

**Comment by danrabbit** [comment]
I'm personally -1 on this. I don't think the results are very good looking and it seems odd to single out music notifications

**Comment by lainsce** [comment]
Music was just an example. Anything that would be sane to have colored notifications would benefit from this.

**Comment by lainsce** [comment]
Another good example is with critical notifications like "Battery is critically low", maybe using our warning colors? :paintbrush:

**Comment by cassidyjames** [comment]
@lainsce that's already something we can do with the priority levels set by notifications today, if we wanted. But that seems pretty aggressive.

**Comment by danrabbit** [comment]
In master critical notifications have red title text

**Comment by lainsce** [comment]
Looking back on it, this was a dumb idea tbh
