### ISSUE TITLE
Play different sound based on `GLib.NotificationPriority`

### ISSUE THREAD

**Issue by marbetschar** [elementary/notifications#75]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

**Play an "alert-type" of sound for "URGENT" notifications, keep the "bing-type" of sound for all others**

A user of my Time Limit app would love to customize the sound of the notification once the timer ended (see https://github.com/marbetschar/time-limit/issues/32).

IMHO it makes a lot of sense to be able to differentiate types of notifications by sound. Although there is already an existing [feature request in GLib](https://gitlab.gnome.org/GNOME/glib/-/issues/1340), the discussion is stalled - somewhere between full sound customization and providing some predefined categories to choose from.

I feel like we can simply use the `GLib.NotificationPriority` to play a different sound per priority. I guess the reasoning is kind of the same as `GLib.NotificationPriority.URGENT` notifications are ignoring Do-Not-Disturb. So at first thought it seems to be appropriate to give it another "sound".

Not quite sure if we should have a unique sound per priority though.

**Comment by cassidyjames** [comment]
Hmm, interesting. I would be open to trying this out.

**Comment by meisenzahl** [comment]
> Hmm, interesting. I would be open to trying this out.

You may want to take a look at my implementation: https://github.com/elementary/notifications/pull/85

**Comment by Marukesu** [comment]
Closed by #85.
