### ISSUE TITLE
KDE like notification ?

### ISSUE THREAD

**Issue by OssNass** [elementary/notifications#78]
I was wondering it is possible to create a notification system similar to KDE's?

Where progress of ongoing operations like copying for example, is shown in real time in the notification instead of a separate window ?!

**Comment by hanaral** [comment]
Apps with prgress indicators can already do that on their icon on the dock.

**Comment by cassidyjames** [comment]
Yeah, I'm inclined to close this as it's too broad, and doesn't really have anything actionable. In elementary OS, apps can integrate with the OS in various ways, oftentimes with FreeDesktop specs. Progress and badge-type indicators make sense in the dock, whereas notifications are for immediate notification, optionally with actions.
