### ISSUE TITLE
Ship a Demo

### ISSUE THREAD

**Issue by danrabbit** [elementary/notifications#90]
Just like we have granite-demo it would be nice to have a demo app to test all the features of the server

**Comment by meisenzahl** [comment]
I added a demo to send notifications in https://github.com/elementary/notifications/pull/85

**Comment by danrabbit** [comment]
@meisenzahl can you split that out into its own branch so it can be reviewed separately please?

**Comment by meisenzahl** [comment]
@danrabbit Sure
