### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by quequotion** [elementary/notifications#91]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
I would like to package a "stable" version of Pantheon Notifications for Archlinux.

**Describe the solution you'd like**
Using git tag, mark a commit to Pantheon Notifications as a "release" and give it a version number. 

**Existing work**
Most of elementary OS's software uses tagged releases to denote "stable" versions, if/when they exist.

**Comment by cassidyjames** [comment]
@quequotion There is not currently a stable release of Notifications, as it does not ship in elementary OS 5.x and will be shipping in elementary OS 6.x (which is not yet out). We will tag a release once we consider it stable, leading up to the 6.x release.

**Comment by efectn** [comment]
You need to package from old commit. Background not working on last commits.

**Comment by quequotion** [comment]
>will be shipping in elementary OS 6.x

Is this happening? I notice the task has slipped off the project page (no longer a "GM" category, removed from any othera; never got done).

**Comment by danrabbit** [comment]
Missed this on Friday on accident. I'll be tagging a release today :)
