### ISSUE TITLE
Notifications can appear outside screen bounds

### ISSUE THREAD

**Issue by clarfonthey** [elementary/notifications#94]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I have a two-monitor setup with a 1440p monitor and a 1080p monitor, where the 1440p monitor is on the left and the 1080p monitor is on the right. The two monitors are aligned at the bottom, rather than on the top, meaning that the two bottoms of the monitor are at the same height. This means that the bounding box containing the total screen real estate has a void area above the right screen. Notifications start appearing on the top left of this "void" area rather than the top left of the right monitor, and you only start to see notifications if they stack high enough to get past this "void."

### To Reproduce
Set up two monitors where one is smaller, the smaller is arranged on the right, and the larger is the primary display. Spam notifications with `notify-send "Hey, listen!"` in the command terminal and you'll see that they start appearing above the monitor on the right.

### Expected behavior

Notifications should not be able to spawn outside the visible area of screens. They should always appear on one of the corners of a visible screen.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context

When I first started with this setup, the monitors were arranged by default with the small monitor as the primary one, on the left. I changed the settings to what I described.

**Comment by hanaral** [comment]
This was already reported on [this issue](https://github.com/elementary/gala/issues/821)

**Comment by clarfonthey** [comment]
Oh! I guess I didn't search hard enough. Will close this then.
